name: Windows Build and Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3
        with:
          path: .

      - name: Node.js yükle
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Server baðýmlýlýklarýný kur
        run: npm install

      - name: Client baðýmlýlýklarýný kur
        run: cd client && npm install

      - name: React arayüzünü üret
        run: cd client && npm run build

      - name: Electron .exe üret
        run: npm run package

      - name: .exe dosyasýný artifact olarak kaydet
        uses: actions/upload-artifact@v4
        with:
          name: emr-cafe-windows-exe
          path: dist/*.exe

      - name: GitHub Release'e yükle
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: EMR Cafe Build ${{ github.run_number }}
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
